<?php

declare(strict_types=1);

use FulltimeTrading\Storage\SqliteRepository;
use FulltimeTrading\Support\ProcessLock;
use FulltimeTrading\Trading\PaperMonitorDecisionGuard;
use FulltimeTrading\Trading\PaperPositionLifecycle;
use FulltimeTrading\Trading\PaperReviewAlertGuard;

require __DIR__ . '/../bootstrap.php';

function expectTrue(bool $condition, string $message): void
{
    if (!$condition) {
        throw new RuntimeException($message);
    }
}

function expectSameValue(mixed $expected, mixed $actual, string $message): void
{
    if ($expected !== $actual) {
        throw new RuntimeException($message . ' Expected ' . var_export($expected, true) . ', got ' . var_export($actual, true) . '.');
    }
}

function expectFloat(float $expected, float $actual, string $message, float $epsilon = 0.000001): void
{
    if (abs($expected - $actual) > $epsilon) {
        throw new RuntimeException($message . ' Expected ' . $expected . ', got ' . $actual . '.');
    }
}

/** @return array<string, mixed> */
function openState(string $symbol = 'USD'): array
{
    return [
        'symbol' => $symbol,
        'status' => 'open',
        'qty' => 150.0,
        'avg_entry_price' => 99.82,
        'market_price' => 95.0,
        'entry_price' => 99.82,
        'stop_price' => 95.89,
        'initial_stop_price' => 87.84,
        'break_even_trigger_price' => 101.81,
        'target_price' => 123.76,
        'break_even_armed' => true,
        'partial_done' => false,
        'strategy' => 'SUPPORT_REGULARITY',
        'setup_key' => 'usd-old-setup',
        'opened_at' => '2026-06-12T13:30:00+00:00',
        'closed_at' => null,
        'last_event_at' => '2026-07-14T12:49:00+00:00',
        'last_action' => 'sync_open',
        'client_order_id' => 'ftt_USD_old_entry',
        'payload' => ['position_lifecycle_id' => 'ftt_USD_old_entry'],
    ];
}

/** @return array<string, mixed> */
function closeStopDecision(float $qty = 150.0): array
{
    return [
        'action' => 'close_stop',
        'severity' => 'warning',
        'reason' => 'USD price 95.00 is at/below stop 95.89.',
        'qty' => $qty,
    ];
}

/** @return array<string, mixed> */
function closeModelDecision(float $qty = 150.0): array
{
    return [
        'action' => 'close_model_missing',
        'severity' => 'warning',
        'reason' => 'USD exists at Alpaca but is absent from model-managed positions.',
        'qty' => $qty,
    ];
}

/** @return array<string, mixed> */
function partialDecision(float $qty = 75.0): array
{
    return [
        'action' => 'partial_take_profit',
        'severity' => 'info',
        'reason' => 'USD reached target 123.76 at 124.00.',
        'qty' => $qty,
    ];
}

$reviewNow = new DateTimeImmutable('2026-07-15T10:00:00+00:00');
$undeliveredReviewState = openState('RISK');
expectTrue(
    !PaperReviewAlertGuard::shouldSuppress($undeliveredReviewState, 'review_risk_source_invalid', $reviewNow, 1440),
    'A review generated by a telegram=false cycle must remain deliverable.',
);
$deliveredReviewState = PaperReviewAlertGuard::markDelivered(
    $undeliveredReviewState,
    'review_risk_source_invalid',
    $reviewNow,
);
expectTrue(
    PaperReviewAlertGuard::shouldSuppress($deliveredReviewState, 'review_risk_source_invalid', $reviewNow->modify('+1 minute'), 1440),
    'A successfully delivered risk-source review must honor its cooldown.',
);
expectTrue(
    !PaperReviewAlertGuard::shouldSuppress($deliveredReviewState, 'review_risk_source_invalid', $reviewNow->modify('+1 day'), 1440),
    'The delivered review cooldown must expire.',
);

/** @param array<string, mixed> $metadata @return array<string, mixed> */
function buyOrderState(string $clientOrderId, string $submittedAt, array $metadata): array
{
    return [
        'client_order_id' => $clientOrderId,
        'symbol' => 'USD',
        'side' => 'buy',
        'type' => 'limit',
        'qty' => 150.0,
        'limit_price' => 91.58,
        'stop_price' => (float) ($metadata['stop'] ?? 0.0),
        'time_in_force' => 'day',
        'status' => 'pending_new',
        'submitted' => true,
        'order_id' => 'alpaca-' . $clientOrderId,
        'source_report' => 'test-report',
        'planned_at' => $submittedAt,
        'submitted_at' => $submittedAt,
        'updated_at' => $submittedAt,
        'payload' => [
            'order' => ['metadata' => $metadata],
            'alpaca_order' => ['filled_at' => null],
        ],
    ];
}

$now = new DateTimeImmutable('2026-07-14T12:50:00+00:00');
$decision = closeStopDecision();
$state = PaperMonitorDecisionGuard::ensureCloseStopEvent(openState(), $decision, $now);
$eventId = PaperMonitorDecisionGuard::eventId($state);
$clientOrderId = PaperMonitorDecisionGuard::clientOrderId($state);

// A pending overnight event may keep the same trigger fingerprint while Alpaca's
// authoritative position grows. Before any external attempt, expand the same stable
// event/client id so an add-on or split is not left behind.
$pendingGrowthState = openState('GROW');
$pendingGrowthState['qty'] = 100.0;
$pendingGrowthDecision = closeStopDecision(100.0);
$pendingGrowthEvent = PaperMonitorDecisionGuard::ensureCloseStopEvent($pendingGrowthState, $pendingGrowthDecision, $now);
$pendingGrowthEventId = PaperMonitorDecisionGuard::eventId($pendingGrowthEvent);
$pendingGrowthClientId = PaperMonitorDecisionGuard::clientOrderId($pendingGrowthEvent);
$pendingGrowthEvent['qty'] = 140.0;
$pendingGrowthEvent = PaperMonitorDecisionGuard::ensureCloseStopEvent($pendingGrowthEvent, $pendingGrowthDecision, $now->modify('+1 minute'));
expectSameValue($pendingGrowthEventId, PaperMonitorDecisionGuard::eventId($pendingGrowthEvent), 'Pending quantity growth must preserve the exit event id.');
expectSameValue($pendingGrowthClientId, PaperMonitorDecisionGuard::clientOrderId($pendingGrowthEvent), 'Pending quantity growth must preserve the stable client id.');
expectFloat(140.0, (float) (PaperMonitorDecisionGuard::event($pendingGrowthEvent)['requested_qty'] ?? 0.0), 'A same-fingerprint pending event must expand to the full new long quantity before submit.');
expectFloat(140.0, PaperMonitorDecisionGuard::remainingExitQty($pendingGrowthEvent, 140.0), 'The expanded pending event must close all 140 shares.');

// After the first full-exit fill, never reinterpret a stale pre-fill snapshot as
// position growth: the immutable 100-share baseline minus 25 known fills is 75.
$staleFullRetry = PaperMonitorDecisionGuard::ensureCloseStopEvent($pendingGrowthState, $pendingGrowthDecision, $now);
$staleFullRetry = PaperMonitorDecisionGuard::markSubmitting($staleFullRetry, $now, 120);
$staleFullRetry = PaperMonitorDecisionGuard::applyOrder($staleFullRetry, [
    'id' => 'stale-full-canceled-25',
    'client_order_id' => PaperMonitorDecisionGuard::clientOrderId($staleFullRetry),
    'symbol' => 'GROW',
    'side' => 'sell',
    'status' => 'canceled',
    'qty' => '100',
    'filled_qty' => '25',
    'time_in_force' => 'day',
], $now, 300);
$staleFullRetry = PaperMonitorDecisionGuard::prepareTerminalRetryIfDue($staleFullRetry, $now->modify('+301 seconds'));
$staleFullRetry['qty'] = 100.0;
$staleFullRetry = PaperMonitorDecisionGuard::ensureCloseStopEvent($staleFullRetry, $pendingGrowthDecision, $now->modify('+302 seconds'));
expectFloat(100.0, (float) (PaperMonitorDecisionGuard::event($staleFullRetry)['requested_qty'] ?? 0.0), 'Known full-exit fills must freeze the original requested baseline.');
expectFloat(75.0, PaperMonitorDecisionGuard::remainingExitQty($staleFullRetry, 100.0), 'A stale 100-share snapshot after a known 25-share fill must retry only 75.');

// The selected mental-stop model must never turn an intraday dip into an initial hard stop.
$mentalState = openState('MENT');
$mentalState['break_even_armed'] = false;
$mentalState['market_price'] = 94.0;
$mentalPolicy = [
    'swing_stop_mode' => 'mental',
    'break_even_stop_mode' => 'hard',
    'mental_stop_exit_on_close' => true,
    'hybrid_hard_stop_symbols' => ['USD'],
];
$intradayMental = PaperMonitorDecisionGuard::evaluateStop($mentalState, $mentalPolicy, 94.0, null, ['hard_stop_active' => false]);
expectTrue(!$intradayMental['triggered'] && $intradayMental['deferred'], 'A mental initial stop must ignore an intraday quote below the stop until a daily close exists.');
$closedMental = PaperMonitorDecisionGuard::evaluateStop($mentalState, $mentalPolicy, 94.0, 95.0, ['hard_stop_active' => false]);
expectTrue($closedMental['triggered'], 'A confirmed daily close below a mental stop must trigger the exit.');
expectSameValue('mental_close', $closedMental['mode'], 'The stop evidence must identify the close-only path.');
$breakEvenState = $mentalState;
$breakEvenState['break_even_armed'] = true;
$hardAfterBreakEven = PaperMonitorDecisionGuard::evaluateStop($breakEvenState, $mentalPolicy, 95.0, null, ['hard_stop_active' => false]);
expectTrue($hardAfterBreakEven['triggered'], 'After BE is armed, the configured hard BE stop must use the live quote.');
expectSameValue('hard_intraday', $hardAfterBreakEven['mode'], 'BE activation must switch the stop to hard intraday mode.');
$closeOnlyBreakEven = PaperMonitorDecisionGuard::evaluateStop(
    $breakEvenState,
    array_merge($mentalPolicy, ['swing_stop_mode' => 'hard', 'break_even_stop_mode' => 'close']),
    95.0,
    null,
    ['hard_stop_active' => true, 'break_even_armed' => true],
);
expectTrue(!$closeOnlyBreakEven['triggered'] && $closeOnlyBreakEven['deferred'], 'An explicit close-only BE rule must not be overridden by the initial hard mode or model hard_stop_active flag.');
$explicitHard = PaperMonitorDecisionGuard::evaluateStop(
    $mentalState,
    array_merge($mentalPolicy, ['swing_stop_mode' => 'hard']),
    95.0,
    null,
    ['hard_stop_active' => false],
);
expectTrue($explicitHard['triggered'], 'An explicitly hard report/config mode must retain intraday stop behavior.');
$modelHard = PaperMonitorDecisionGuard::evaluateStop($mentalState, $mentalPolicy, 95.0, null, ['hard_stop_active' => true]);
expectTrue($modelHard['triggered'], 'Explicit model hard_stop_active metadata must retain intraday protection.');
$mentalDecision = closeStopDecision();
$mentalDecision['stop_trigger_mode'] = 'mental_close';
$mentalDecision['stop_trigger_price'] = 95.0;
$mentalDecision['stop_trigger_bar_date'] = '2026-07-14';
$latchedMental = PaperMonitorDecisionGuard::ensureCloseStopEvent($mentalState, $mentalDecision, $now);
expectTrue(PaperMonitorDecisionGuard::isLatchedMentalStop($latchedMental), 'A close-confirmed mental stop must remain latched for the next market-open submit.');

// Premarket + restart: one stable event/attempt and no permanent suppression before Telegram delivery.
expectSameValue('pending', PaperMonitorDecisionGuard::phase($state), 'The first premarket stop must be pending.');
expectTrue($eventId !== '', 'The pending event must have an id.');
expectTrue(strlen($clientOrderId) <= 48, 'The stable Alpaca client_order_id must fit the 48 character limit.');
expectTrue(!PaperMonitorDecisionGuard::maySubmit($state, false), 'Premarket canSubmit=false must block submit.');
$pendingAlertKey = PaperMonitorDecisionGuard::alertKey($state, 'pending');
expectSameValue('pending:1', $pendingAlertKey, 'Pending alert keys must be attempt-scoped.');
expectTrue(PaperMonitorDecisionGuard::shouldEmitAlert($state, $pendingAlertKey), 'telegram=false must leave the first alert undelivered.');
expectTrue(PaperMonitorDecisionGuard::shouldLogAction($state, $pendingAlertKey), 'The first event phase must write one action row.');
$state = PaperMonitorDecisionGuard::markActionLogged($state, $eventId, $pendingAlertKey, $now);
expectTrue(!PaperMonitorDecisionGuard::shouldLogAction($state, $pendingAlertKey), 'Action logging must be independent and deduplicated.');
expectTrue(PaperMonitorDecisionGuard::shouldEmitAlert($state, $pendingAlertKey), 'Logging an action must not suppress a later Telegram alert.');
expectTrue(PaperMonitorDecisionGuard::needsPlannedOrderPersistence($state, 'blocked_market_closed'), 'The first pending attempt must persist its plan.');
$state = PaperMonitorDecisionGuard::markPlannedOrderPersisted($state, 'blocked_market_closed', $now);
expectTrue(!PaperMonitorDecisionGuard::needsPlannedOrderPersistence($state, 'blocked_market_closed'), 'The same pending attempt must not upsert its plan every poll.');

$databasePath = tempnam(sys_get_temp_dir(), 'ftt-paper-monitor-');
if ($databasePath === false) {
    throw new RuntimeException('Unable to allocate a temporary SQLite path.');
}

try {
    $repo = new SqliteRepository($databasePath);
    $repo->migrate();

    // Target partial: persist-before-HTTP and restart reconciliation must be idempotent.
    $partialNow = new DateTimeImmutable('2026-07-15T15:00:00+00:00');
    $partialBase = PaperMonitorDecisionGuard::ensurePartialEvent(openState('PTA'), partialDecision(), $partialNow);
    $partialClientId = PaperMonitorDecisionGuard::partialClientOrderId($partialBase);
    expectTrue($partialClientId !== '' && strlen($partialClientId) <= 48, 'A target partial needs one stable Alpaca client id.');
    expectFloat(75.0, PaperMonitorDecisionGuard::partialRemainingQty($partialBase, 150.0), 'The initial target partial must reserve exactly its requested qty.');
    $partialPendingAlertKey = PaperMonitorDecisionGuard::partialAlertKey($partialBase, 'pending');
    $partialEventId = (string) (PaperMonitorDecisionGuard::partialEvent($partialBase)['event_id'] ?? '');
    expectSameValue('pending:1', $partialPendingAlertKey, 'Partial alert keys must be attempt-scoped.');
    expectTrue(PaperMonitorDecisionGuard::shouldLogPartialAction($partialBase, $partialPendingAlertKey), 'The first partial phase must write one action row.');
    $partialAlertState = PaperMonitorDecisionGuard::markPartialActionLogged($partialBase, $partialEventId, $partialPendingAlertKey, $partialNow);
    expectTrue(!PaperMonitorDecisionGuard::shouldLogPartialAction($partialAlertState, $partialPendingAlertKey), 'Repeated closed-market partial polls must not duplicate action rows.');
    $partialAlertState = PaperMonitorDecisionGuard::markPartialAlertAttempted($partialAlertState, $partialEventId, $partialPendingAlertKey, $partialNow);
    expectTrue(
        !PaperMonitorDecisionGuard::shouldEmitPartialAlert($partialAlertState, $partialPendingAlertKey, $partialNow->modify('+899 seconds'), 900),
        'A failed partial Telegram attempt must honor the alert cooldown.',
    );
    expectTrue(
        PaperMonitorDecisionGuard::shouldEmitPartialAlert($partialAlertState, $partialPendingAlertKey, $partialNow->modify('+900 seconds'), 900),
        'An undelivered partial alert must become retryable after the cooldown.',
    );
    $partialAlertState = PaperMonitorDecisionGuard::markPartialAlertDelivered($partialAlertState, $partialEventId, $partialPendingAlertKey, $partialNow->modify('+901 seconds'));
    expectTrue(
        !PaperMonitorDecisionGuard::shouldEmitPartialAlert($partialAlertState, $partialPendingAlertKey, $partialNow->modify('+1 day'), 900),
        'A delivered partial phase alert must remain deduplicated.',
    );
    $partialSubmitting = PaperMonitorDecisionGuard::markPartialSubmitting($partialBase, $partialNow, 120);
    $repo->savePaperPositionState($partialSubmitting);
    $partialRestarted = $repo->loadPaperPositionStates()['PTA'] ?? [];
    expectSameValue($partialClientId, PaperMonitorDecisionGuard::partialClientOrderId($partialRestarted), 'A crash after persistence must retain the partial client id.');
    expectSameValue('submitting', PaperMonitorDecisionGuard::partialPhase($partialRestarted), 'A restarted ambiguous partial must remain submitting.');
    expectTrue(!PaperMonitorDecisionGuard::partialMaySubmit($partialRestarted, true, 75.0), 'A restarted submitting partial must not create a duplicate sell.');
    $partialAcceptedOrder = [
        'id' => 'partial-accepted-1',
        'client_order_id' => $partialClientId,
        'symbol' => 'PTA',
        'side' => 'sell',
        'status' => 'accepted',
        'qty' => '75',
        'filled_qty' => '0',
        'time_in_force' => 'day',
    ];
    expectSameValue(
        'partial-accepted-1',
        PaperMonitorDecisionGuard::activeSellOrder([$partialAcceptedOrder], 'PTA', $partialClientId)['id'] ?? null,
        'Restart reconciliation must find its accepted partial by stable client id.',
    );
    $partialInflight = PaperMonitorDecisionGuard::applyPartialOrder($partialRestarted, $partialAcceptedOrder, $partialNow->modify('+5 seconds'), 300);
    expectSameValue('inflight', PaperMonitorDecisionGuard::partialPhase($partialInflight), 'An accepted target partial remains inflight.');
    expectTrue(!(bool) ($partialInflight['partial_done'] ?? false), 'Accepted is not filled: partial_done must remain false.');
    expectTrue(!PaperMonitorDecisionGuard::partialMaySubmit($partialInflight, true, 75.0), 'An inflight target partial must suppress every duplicate submit.');
    $partialInflightAgain = PaperMonitorDecisionGuard::ensurePartialEvent($partialInflight, partialDecision(), $partialNow->modify('+1 minute'));
    expectSameValue($partialClientId, PaperMonitorDecisionGuard::partialClientOrderId($partialInflightAgain), 'Repeated target detection must retain the accepted partial attempt.');
    $partialAmbiguous = PaperMonitorDecisionGuard::markPartialAmbiguousSubmit($partialSubmitting, 'timeout', $partialNow, 120);
    $partialAmbiguousEarly = PaperMonitorDecisionGuard::releasePartialAmbiguousAttemptIfDue($partialAmbiguous, $partialNow->modify('+119 seconds'));
    expectSameValue('submitting', PaperMonitorDecisionGuard::partialPhase($partialAmbiguousEarly), 'An ambiguous partial must stay guarded during its reconciliation window.');
    $partialAmbiguousRetry = PaperMonitorDecisionGuard::releasePartialAmbiguousAttemptIfDue($partialAmbiguous, $partialNow->modify('+121 seconds'));
    expectSameValue('pending', PaperMonitorDecisionGuard::partialPhase($partialAmbiguousRetry), 'An unresolved ambiguous partial may retry only after reconciliation delay.');
    expectSameValue($partialClientId, PaperMonitorDecisionGuard::partialClientOrderId($partialAmbiguousRetry), 'An ambiguous partial retry must reuse the exact same client id.');

    $partialForeignBase = PaperMonitorDecisionGuard::ensurePartialEvent(openState('PTB'), partialDecision(), $partialNow);
    $partialForeignSell = [
        'id' => 'partial-foreign-active',
        'client_order_id' => 'manual-partial-sell',
        'symbol' => 'PTB',
        'side' => 'sell',
        'status' => 'accepted',
        'qty' => '30',
        'filled_qty' => '0',
        'time_in_force' => 'day',
    ];
    $partialForeignBlocked = PaperMonitorDecisionGuard::markPartialBlockedByActiveSell($partialForeignBase, $partialForeignSell, 150.0, $partialNow);
    expectSameValue('blocked_active_sell', PaperMonitorDecisionGuard::partialPhase($partialForeignBlocked), 'Any other active sell must reserve quantity before a target partial can submit.');
    expectTrue(!PaperMonitorDecisionGuard::partialMaySubmit($partialForeignBlocked, true, 75.0), 'A foreign active sell must block the target partial from double-selling quantity.');
    $partialForeignStillActive = PaperMonitorDecisionGuard::reconcilePartialActiveSellBlock(
        $partialForeignBlocked,
        array_merge($partialForeignSell, ['status' => 'partially_filled', 'filled_qty' => '10']),
        140.0,
        $partialNow->modify('+30 seconds'),
    );
    expectTrue(PaperMonitorDecisionGuard::partialActiveSellBlock($partialForeignStillActive) !== null, 'A reflected partial fill must not release a still-active sell remainder.');
    $partialForeignReleased = PaperMonitorDecisionGuard::reconcilePartialActiveSellBlock(
        $partialForeignStillActive,
        array_merge($partialForeignSell, ['status' => 'canceled', 'filled_qty' => '10']),
        140.0,
        $partialNow->modify('+1 minute'),
    );
    expectSameValue(null, PaperMonitorDecisionGuard::partialActiveSellBlock($partialForeignReleased), 'A terminal foreign sell may release only after its fill is reflected by the position snapshot.');
    expectSameValue('pending', PaperMonitorDecisionGuard::partialPhase($partialForeignReleased), 'After safe foreign-order reconciliation, the original partial attempt may resume.');

    // A 25/75 terminal fill retries at most 50 even with a stale 150-share snapshot.
    $partialFillBase = PaperMonitorDecisionGuard::ensurePartialEvent(openState('PTF'), partialDecision(), $partialNow);
    $partialFillBase = PaperMonitorDecisionGuard::markPartialSubmitting($partialFillBase, $partialNow, 120);
    $partialFillAttempt1 = PaperMonitorDecisionGuard::applyPartialOrder($partialFillBase, [
        'id' => 'partial-canceled-25',
        'client_order_id' => PaperMonitorDecisionGuard::partialClientOrderId($partialFillBase),
        'symbol' => 'PTF',
        'side' => 'sell',
        'status' => 'canceled',
        'qty' => '75',
        'filled_qty' => '25',
        'time_in_force' => 'day',
    ], $partialNow, 300);
    expectSameValue('retry_wait', PaperMonitorDecisionGuard::partialPhase($partialFillAttempt1), 'A partially filled canceled target order must enter retry_wait.');
    expectTrue(!(bool) ($partialFillAttempt1['partial_done'] ?? false), '25 of target 75 must not arm partial_done.');
    expectFloat(50.0, PaperMonitorDecisionGuard::partialRemainingQty($partialFillAttempt1, 150.0), 'A stale position snapshot must not restore the already filled 25 shares.');
    expectFloat(125.0, PaperMonitorDecisionGuard::positionQtyAfterKnownPartialFills($partialFillAttempt1, 150.0), 'A full stop must also deduct known target fills from a stale position snapshot.');
    $partialSnapshot25 = PaperMonitorDecisionGuard::syncPartialPosition($partialFillAttempt1, 125.0, $partialNow->modify('+1 second'));
    expectFloat(50.0, PaperMonitorDecisionGuard::partialRemainingQty($partialSnapshot25, 125.0), 'Position confirmation and order filled_qty must not count the same 25 twice.');
    expectFloat(125.0, PaperMonitorDecisionGuard::positionQtyAfterKnownPartialFills($partialSnapshot25, 125.0), 'Once the target fill is reflected, the snapshot must remain the full current long quantity.');

    // A later add-on may still be below the pre-partial baseline. Once the earlier
    // fill was position-confirmed, the new observed qty must not be capped away.
    $partialAfterAddOn = PaperMonitorDecisionGuard::syncPartialPosition($partialSnapshot25, 140.0, $partialNow->modify('+2 seconds'));
    expectFloat(140.0, PaperMonitorDecisionGuard::positionQtyAfterKnownPartialFills($partialAfterAddOn, 140.0), 'A confirmed add-on/new position quantity must be included in a full stop.');
    $fullAfterAddOn = PaperMonitorDecisionGuard::ensureCloseStopEvent($partialAfterAddOn, closeStopDecision(140.0), $partialNow->modify('+3 seconds'));
    expectFloat(140.0, (float) (PaperMonitorDecisionGuard::event($fullAfterAddOn)['requested_qty'] ?? 0.0), 'The full-exit event must request the entire reconciled long quantity after an add-on.');

    // The full-exit event starts from the post-partial safe qty. Its own partial fill
    // must then be deducted once even if Alpaca still returns the pre-fill position.
    $fullRetryAfterPartial = PaperMonitorDecisionGuard::ensureCloseStopEvent($partialFillAttempt1, closeStopDecision(125.0), $partialNow->modify('+4 seconds'));
    $fullRetryAfterPartial = PaperMonitorDecisionGuard::markSubmitting($fullRetryAfterPartial, $partialNow->modify('+4 seconds'), 120);
    $fullRetryAfterPartial = PaperMonitorDecisionGuard::applyOrder($fullRetryAfterPartial, [
        'id' => 'full-after-partial-canceled-25',
        'client_order_id' => PaperMonitorDecisionGuard::clientOrderId($fullRetryAfterPartial),
        'symbol' => 'PTF',
        'side' => 'sell',
        'status' => 'canceled',
        'qty' => '125',
        'filled_qty' => '25',
        'time_in_force' => 'day',
    ], $partialNow->modify('+5 seconds'), 300);
    expectFloat(
        100.0,
        PaperMonitorDecisionGuard::remainingExitQty(
            $fullRetryAfterPartial,
            PaperMonitorDecisionGuard::positionQtyAfterKnownPartialFills($fullRetryAfterPartial, 150.0),
        ),
        'A stale position snapshot after target and full-exit fills must retry only the true 100-share remainder.',
    );

    $fullAfterPartial = PaperMonitorDecisionGuard::ensureCloseStopEvent($partialSnapshot25, closeStopDecision(125.0), $partialNow->modify('+6 seconds'));
    $fullAfterPartial = PaperMonitorDecisionGuard::markBlockedByActiveSell($fullAfterPartial, [
        'id' => 'partial-canceled-25',
        'client_order_id' => PaperMonitorDecisionGuard::partialClientOrderId($partialFillAttempt1),
        'symbol' => 'PTF',
        'side' => 'sell',
        'status' => 'partially_filled',
        'qty' => '75',
        'filled_qty' => '25',
        'time_in_force' => 'day',
    ], 125.0, $partialNow->modify('+2 seconds'));
    $fullAfterPartial = PaperMonitorDecisionGuard::reconcileActiveSellBlock($fullAfterPartial, [
        'id' => 'partial-canceled-25',
        'client_order_id' => PaperMonitorDecisionGuard::partialClientOrderId($partialFillAttempt1),
        'symbol' => 'PTF',
        'side' => 'sell',
        'status' => 'canceled',
        'qty' => '75',
        'filled_qty' => '25',
        'time_in_force' => 'day',
    ], 125.0, $partialNow->modify('+3 seconds'));
    expectFloat(
        125.0,
        PaperMonitorDecisionGuard::remainingExitQty(
            $fullAfterPartial,
            PaperMonitorDecisionGuard::positionQtyAfterKnownPartialFills($fullAfterPartial, 125.0),
        ),
        'Full-exit and target-partial fill evidence must converge on 125, not double-deduct to 100.',
    );
    $partialFillRetry = PaperMonitorDecisionGuard::preparePartialRetryIfDue($partialSnapshot25, $partialNow->modify('+301 seconds'));
    $partialRetryClientId = PaperMonitorDecisionGuard::partialClientOrderId($partialFillRetry);
    expectTrue($partialRetryClientId !== PaperMonitorDecisionGuard::partialClientOrderId($partialFillAttempt1), 'A terminal retry must rotate to attempt two after backoff.');
    expectFloat(50.0, PaperMonitorDecisionGuard::partialRemainingQty($partialFillRetry, 150.0), 'Attempt two may sell at most the unfilled target remainder.');
    $partialFillRetryAgain = PaperMonitorDecisionGuard::ensurePartialEvent($partialFillRetry, partialDecision(), $partialNow->modify('+302 seconds'));
    expectSameValue($partialRetryClientId, PaperMonitorDecisionGuard::partialClientOrderId($partialFillRetryAgain), 'Attempt two client id must remain stable across another poll/restart.');
    $partialFilled = PaperMonitorDecisionGuard::applyPartialOrder($partialFillRetryAgain, [
        'id' => 'partial-filled-50',
        'client_order_id' => $partialRetryClientId,
        'symbol' => 'PTF',
        'side' => 'sell',
        'status' => 'filled',
        'qty' => '50',
        'filled_qty' => '50',
        'time_in_force' => 'day',
    ], $partialNow->modify('+303 seconds'), 300);
    expectSameValue('filled', PaperMonitorDecisionGuard::partialPhase($partialFilled), 'The 25 + 50 fills must complete the target partial.');
    expectTrue((bool) ($partialFilled['partial_done'] ?? false), 'partial_done may arm only after all target quantity is filled.');
    expectFloat(0.0, PaperMonitorDecisionGuard::partialRemainingQty($partialFilled, 150.0), 'A completed target partial has no retry quantity.');
    expectTrue(!PaperMonitorDecisionGuard::partialMaySubmit($partialFilled, true, 50.0), 'A filled target event must permanently suppress duplicate sells for this lifecycle.');
    $unprovenFilledBase = PaperMonitorDecisionGuard::ensurePartialEvent(openState('PTU'), partialDecision(), $partialNow);
    $unprovenFilled = PaperMonitorDecisionGuard::applyPartialOrder($unprovenFilledBase, [
        'id' => 'partial-filled-without-evidence',
        'client_order_id' => PaperMonitorDecisionGuard::partialClientOrderId($unprovenFilledBase),
        'symbol' => 'PTU',
        'side' => 'sell',
        'status' => 'filled',
        'qty' => '75',
        'filled_qty' => '0',
        'time_in_force' => 'day',
    ], $partialNow, 300);
    expectSameValue('suspended', PaperMonitorDecisionGuard::partialPhase($unprovenFilled), 'A filled label without qty/snapshot evidence must fail closed.');
    expectTrue(!(bool) ($unprovenFilled['partial_done'] ?? false), 'A terminal label alone must never arm partial_done.');
    expectTrue(!PaperMonitorDecisionGuard::partialMaySubmit($unprovenFilled, true, 75.0), 'Unproven terminal quantity must not be retried into a possible short.');
    $snapshotConfirmedBase = PaperMonitorDecisionGuard::ensurePartialEvent(openState('PTS'), partialDecision(), $partialNow);
    $snapshotConfirmed = PaperMonitorDecisionGuard::syncPartialPosition($snapshotConfirmedBase, 75.0, $partialNow->modify('+1 minute'));
    expectSameValue('filled', PaperMonitorDecisionGuard::partialPhase($snapshotConfirmed), 'A position reduction equal to the complete target qty may confirm completion after a crash.');
    expectTrue((bool) ($snapshotConfirmed['partial_done'] ?? false), 'A complete position-snapshot confirmation may arm partial_done without an order response.');

    // A zero-fill cancellation gets a new, stable retry attempt without changing target qty.
    $zeroFillBase = PaperMonitorDecisionGuard::ensurePartialEvent(openState('PTZ'), partialDecision(), $partialNow);
    $zeroFillAttempt1Id = PaperMonitorDecisionGuard::partialClientOrderId($zeroFillBase);
    $zeroFillRetryWait = PaperMonitorDecisionGuard::applyPartialOrder($zeroFillBase, [
        'id' => 'partial-canceled-zero',
        'client_order_id' => $zeroFillAttempt1Id,
        'symbol' => 'PTZ',
        'side' => 'sell',
        'status' => 'canceled',
        'qty' => '75',
        'filled_qty' => '0',
        'time_in_force' => 'day',
    ], $partialNow, 300);
    expectFloat(75.0, PaperMonitorDecisionGuard::partialRemainingQty($zeroFillRetryWait, 150.0), 'A zero-fill cancellation must preserve the full target remainder.');
    $zeroFillRetry = PaperMonitorDecisionGuard::preparePartialRetryIfDue($zeroFillRetryWait, $partialNow->modify('+301 seconds'));
    $zeroFillAttempt2Id = PaperMonitorDecisionGuard::partialClientOrderId($zeroFillRetry);
    expectTrue($zeroFillAttempt2Id !== $zeroFillAttempt1Id, 'A terminal zero-fill retry must use a new attempt id.');
    $zeroFillRetryPoll = PaperMonitorDecisionGuard::ensurePartialEvent($zeroFillRetry, partialDecision(), $partialNow->modify('+302 seconds'));
    expectSameValue($zeroFillAttempt2Id, PaperMonitorDecisionGuard::partialClientOrderId($zeroFillRetryPoll), 'The second zero-fill attempt id must be stable until HTTP submit/reconciliation.');
    $zeroFillSubmitting = PaperMonitorDecisionGuard::markPartialSubmitting($zeroFillRetryPoll, $partialNow->modify('+303 seconds'), 120);
    expectTrue(!PaperMonitorDecisionGuard::partialMaySubmit($zeroFillSubmitting, true, 75.0), 'Once attempt two is persisted as submitting, another poll cannot double-sell.');

    $repo->savePaperPositionState($state);
    $restartedState = $repo->loadPaperPositionStates()['USD'] ?? [];
    expectSameValue($clientOrderId, PaperMonitorDecisionGuard::clientOrderId($restartedState), 'Restart must keep the stable attempt id.');
    expectTrue(PaperMonitorDecisionGuard::shouldEmitAlert($restartedState, $pendingAlertKey), 'A silent monitor must not suppress a later Telegram alert.');
    expectTrue(!PaperMonitorDecisionGuard::needsPlannedOrderPersistence($restartedState, 'blocked_market_closed'), 'The persisted plan marker must survive restart.');

    $attemptedState = PaperMonitorDecisionGuard::markAlertAttempted($restartedState, $eventId, $pendingAlertKey, $now);
    expectTrue(
        !PaperMonitorDecisionGuard::shouldEmitAlert($attemptedState, $pendingAlertKey, $now->modify('+899 seconds'), 900),
        'A failed Telegram attempt must be cooled down to prevent one-minute retries.',
    );
    expectTrue(
        PaperMonitorDecisionGuard::shouldEmitAlert($attemptedState, $pendingAlertKey, $now->modify('+900 seconds'), 900),
        'An undelivered Telegram alert must become retryable after the cooldown.',
    );
    expectTrue(!PaperMonitorDecisionGuard::shouldLogAction($attemptedState, $pendingAlertKey), 'Telegram retries must not duplicate the action log.');

    $deliveredState = PaperMonitorDecisionGuard::markAlertDelivered($attemptedState, $eventId, $pendingAlertKey, $now->modify('+901 seconds'));
    $repo->savePaperPositionState($deliveredState);
    $deliveredState = $repo->loadPaperPositionStates()['USD'] ?? [];
    expectTrue(!PaperMonitorDecisionGuard::shouldEmitAlert($deliveredState, $pendingAlertKey, $now->modify('+1 day'), 900), 'Successful Telegram delivery must permanently suppress that attempt-phase alert.');
    $pendingAlert = PaperMonitorDecisionGuard::event($deliveredState)['alerts'][$pendingAlertKey] ?? [];
    expectTrue(isset($pendingAlert['action_logged_at'], $pendingAlert['attempted_at'], $pendingAlert['delivered_at']), 'Alert state must preserve independent action, attempt, and delivery timestamps.');

    $updatedQuote = $deliveredState;
    $updatedQuote['market_price'] = 94.75;
    $updatedDecision = $decision;
    $updatedDecision['reason'] = 'USD price 94.75 is at/below stop 95.89.';
    $updatedQuote = PaperMonitorDecisionGuard::ensureCloseStopEvent($updatedQuote, $updatedDecision, $now->modify('+1 minute'));
    expectSameValue($eventId, PaperMonitorDecisionGuard::eventId($updatedQuote), 'Quote changes below one stop must keep the same event.');
    expectSameValue($clientOrderId, PaperMonitorDecisionGuard::clientOrderId($updatedQuote), 'Quote changes must keep the stable attempt id.');

    // Open dry-run/guarded mode is blocked, but uses a distinct deliverable alert.
    expectTrue(!PaperMonitorDecisionGuard::maySubmit($updatedQuote, false), 'Open dry-run/guarded mode must not submit.');
    $blockedAlertKey = PaperMonitorDecisionGuard::alertKey($updatedQuote, 'blocked');
    expectTrue(PaperMonitorDecisionGuard::shouldEmitAlert($updatedQuote, $blockedAlertKey), 'Open blocked mode must have its own alert.');

    // Accepted submit stays inflight; a stale position and an active sell cannot produce a second sell.
    $submittingState = PaperMonitorDecisionGuard::markSubmitting($updatedQuote, $now->modify('+40 minutes'), 120);
    expectSameValue('submitting', PaperMonitorDecisionGuard::phase($submittingState), 'Attempt must be persisted as submitting before HTTP submit.');
    expectTrue(!PaperMonitorDecisionGuard::maySubmit($submittingState, true), 'Submitting phase must block duplicate submit.');
    $acceptedOrder = [
        'id' => 'close-order-1',
        'client_order_id' => $clientOrderId,
        'symbol' => 'USD',
        'side' => 'sell',
        'status' => 'pending_new',
        'qty' => '150',
    ];
    $inflightState = PaperMonitorDecisionGuard::applyOrder($submittingState, $acceptedOrder, $now->modify('+40 minutes 2 seconds'), 300);
    expectSameValue('inflight', PaperMonitorDecisionGuard::phase($inflightState), 'Accepted close order must stay inflight.');
    expectTrue(!PaperMonitorDecisionGuard::maySubmit($inflightState, true), 'Inflight phase must block a second full-qty sell.');
    expectSameValue('close-order-1', PaperMonitorDecisionGuard::activeSellOrder([$acceptedOrder], 'USD')['id'] ?? null, 'Any active sell for the symbol must be a hard guard.');
    $stalePositionState = PaperMonitorDecisionGuard::ensureCloseStopEvent($inflightState, $updatedDecision, $now->modify('+41 minutes'));
    expectSameValue($clientOrderId, PaperMonitorDecisionGuard::clientOrderId($stalePositionState), 'A stale position snapshot must retain the accepted attempt.');
    expectTrue(!PaperMonitorDecisionGuard::maySubmit($stalePositionState, true), 'Accepted order plus stale position must not submit again.');
    expectSameValue('inflight', PaperMonitorDecisionGuard::phase(PaperMonitorDecisionGuard::clearRecoveredCloseStop($stalePositionState)), 'Price recovery cannot clear an inflight exit order.');

    $submittedAlertKey = PaperMonitorDecisionGuard::alertKey($stalePositionState, 'submitted');
    expectTrue(PaperMonitorDecisionGuard::shouldEmitAlert($stalePositionState, $submittedAlertKey), 'An accepted order alert remains deliverable after telegram=false.');
    $stalePositionState = PaperMonitorDecisionGuard::markAlertDelivered($stalePositionState, $eventId, $submittedAlertKey, $now);
    expectTrue(!PaperMonitorDecisionGuard::shouldEmitAlert($stalePositionState, $submittedAlertKey), 'Delivered accepted alert must be deduplicated.');

    // A different active sell blocks quantity without being adopted as this event's order.
    $blockBase = PaperMonitorDecisionGuard::ensureCloseStopEvent(openState('BLK'), closeStopDecision(), $now);
    $blockEventId = PaperMonitorDecisionGuard::eventId($blockBase);
    $blockClientOrderId = PaperMonitorDecisionGuard::clientOrderId($blockBase);
    $foreignOrder = [
        'id' => 'foreign-sell-1',
        'client_order_id' => 'manual-sell-1',
        'symbol' => 'BLK',
        'side' => 'sell',
        'status' => 'partially_filled',
        'qty' => '150',
        'filled_qty' => '25',
        'time_in_force' => 'gtc',
    ];
    $ownOrder = [
        'id' => 'own-sell-1',
        'client_order_id' => $blockClientOrderId,
        'symbol' => 'BLK',
        'side' => 'sell',
        'status' => 'accepted',
        'qty' => '150',
        'filled_qty' => '0',
        'time_in_force' => 'day',
    ];
    expectSameValue(
        'own-sell-1',
        PaperMonitorDecisionGuard::activeSellOrder([$foreignOrder, $ownOrder], 'BLK', $blockClientOrderId)['id'] ?? null,
        'The monitor must prefer its own active order when multiple sells exist.',
    );
    $blockedState = PaperMonitorDecisionGuard::markBlockedByActiveSell($blockBase, $foreignOrder, 150.0, $now);
    expectSameValue('blocked_active_sell', PaperMonitorDecisionGuard::phase($blockedState), 'A foreign active sell must block a new full exit.');
    expectSameValue($blockEventId, PaperMonitorDecisionGuard::eventId($blockedState), 'A foreign sell must not replace the persistent exit event.');
    expectSameValue($blockClientOrderId, PaperMonitorDecisionGuard::clientOrderId($blockedState), 'A foreign sell must not overwrite the event client id.');
    expectSameValue('', (string) (PaperMonitorDecisionGuard::event($blockedState)['order_id'] ?? ''), 'A foreign sell must not be adopted as the event order.');
    expectTrue(!PaperMonitorDecisionGuard::maySubmit($blockedState, true), 'Blocked quantity must never permit a concurrent sell.');

    $changedWhileBlocked = $blockedState;
    $changedWhileBlocked['stop_price'] = 96.25;
    $changedWhileBlocked = PaperMonitorDecisionGuard::ensureCloseStopEvent(
        $changedWhileBlocked,
        closeModelDecision(),
        $now->modify('+1 minute'),
    );
    expectSameValue($blockEventId, PaperMonitorDecisionGuard::eventId($changedWhileBlocked), 'Changed stop/action must not discard an unresolved active-sell blocker.');
    expectSameValue('blocked_active_sell', PaperMonitorDecisionGuard::phase($changedWhileBlocked), 'The unresolved blocker phase must survive a changed fingerprint.');
    expectSameValue('manual-sell-1', PaperMonitorDecisionGuard::activeSellBlock($changedWhileBlocked)['client_order_id'] ?? null, 'The persisted blocker reference must survive a changed fingerprint.');

    $filledButStale = PaperMonitorDecisionGuard::reconcileActiveSellBlock(
        $changedWhileBlocked,
        array_merge($foreignOrder, ['status' => 'filled', 'filled_qty' => '150']),
        150.0,
        $now->modify('+2 minutes'),
    );
    expectTrue(PaperMonitorDecisionGuard::activeSellBlock($filledButStale) !== null, 'A filled foreign sell with unchanged stale position qty must remain guarded.');
    $reducedAfterFill = PaperMonitorDecisionGuard::reconcileActiveSellBlock(
        $filledButStale,
        array_merge($foreignOrder, ['status' => 'filled', 'filled_qty' => '150']),
        100.0,
        $now->modify('+3 minutes'),
    );
    expectSameValue(null, PaperMonitorDecisionGuard::activeSellBlock($reducedAfterFill), 'Observed position reduction must release the foreign-sell blocker.');
    expectSameValue('filled', PaperMonitorDecisionGuard::phase($reducedAfterFill), 'A fully filled foreign exit must remain latched until the position disappears, even if a stale snapshot only partially shrinks.');
    $newFingerprintEvent = PaperMonitorDecisionGuard::ensureCloseStopEvent($reducedAfterFill, closeModelDecision(), $now->modify('+4 minutes'));
    expectSameValue($blockEventId, PaperMonitorDecisionGuard::eventId($newFingerprintEvent), 'A changed exit action must not replace a filled foreign-exit guard while a position snapshot remains.');

    $canceledBlock = PaperMonitorDecisionGuard::markBlockedByActiveSell($blockBase, $foreignOrder, 150.0, $now);
    $canceledBlock = PaperMonitorDecisionGuard::reconcileActiveSellBlock(
        $canceledBlock,
        array_merge($foreignOrder, ['status' => 'canceled']),
        150.0,
        $now,
    );
    expectSameValue(null, PaperMonitorDecisionGuard::activeSellBlock($canceledBlock), 'Canceled foreign sells must release the blocker.');
    expectFloat(
        125.0,
        PaperMonitorDecisionGuard::remainingExitQty($canceledBlock, 150.0),
        'A terminal foreign partial fill must reduce the safe exit qty even while the Alpaca position snapshot is stale.',
    );
    $partialBlock = PaperMonitorDecisionGuard::markBlockedByActiveSell($blockBase, $foreignOrder, 150.0, $now);
    $partialBlock = PaperMonitorDecisionGuard::reconcileActiveSellBlock($partialBlock, $foreignOrder, 125.0, $now);
    expectSameValue(null, PaperMonitorDecisionGuard::activeSellBlock($partialBlock), 'A partial fill reflected in lower position qty must release the stale full-qty blocker.');
    expectFloat(125.0, PaperMonitorDecisionGuard::remainingExitQty($partialBlock, 125.0), 'A reflected partial fill must still be recorded so an intermediate stale snapshot cannot restore sold quantity.');
    $remainingExit = PaperMonitorDecisionGuard::ensureCloseStopEvent($partialBlock, closeStopDecision(125.0), $now->modify('+1 second'));
    expectSameValue($blockEventId, PaperMonitorDecisionGuard::eventId($remainingExit), 'Known partial fills must keep the original event so a changed snapshot cannot restore sold quantity.');
    $remainingExit = PaperMonitorDecisionGuard::markBlockedByActiveSell($remainingExit, $foreignOrder, 125.0, $now->modify('+1 second'));
    expectSameValue('blocked_active_sell', PaperMonitorDecisionGuard::phase($remainingExit), 'An active partially-filled order must continue blocking the new remaining event.');

    $ownSelectedState = PaperMonitorDecisionGuard::applyOrder(PaperMonitorDecisionGuard::clearActiveSellBlock($blockedState), $ownOrder, $now, 300);
    expectSameValue('inflight', PaperMonitorDecisionGuard::phase($ownSelectedState), 'The event may adopt only its own matching active order.');
    expectSameValue('own-sell-1', PaperMonitorDecisionGuard::event($ownSelectedState)['order_id'] ?? null, 'Matching client id must reconcile the event order id.');

    // Ambiguous submit is reconciled with the same id before any retry is allowed.
    $ambiguousBase = PaperMonitorDecisionGuard::ensureCloseStopEvent(openState('AMB'), closeStopDecision(), $now);
    $ambiguousId = PaperMonitorDecisionGuard::clientOrderId($ambiguousBase);
    $ambiguousState = PaperMonitorDecisionGuard::markSubmitting($ambiguousBase, $now, 120);
    $ambiguousState = PaperMonitorDecisionGuard::markAmbiguousSubmit($ambiguousState, 'timeout', $now, 120);
    $tooEarly = PaperMonitorDecisionGuard::releaseAmbiguousAttemptIfDue($ambiguousState, $now->modify('+119 seconds'));
    expectSameValue('submitting', PaperMonitorDecisionGuard::phase($tooEarly), 'Ambiguous submit must remain guarded during reconciliation delay.');
    $released = PaperMonitorDecisionGuard::releaseAmbiguousAttemptIfDue($ambiguousState, $now->modify('+121 seconds'));
    expectSameValue('pending', PaperMonitorDecisionGuard::phase($released), 'An unreconciled attempt may retry only after the delay.');
    expectSameValue($ambiguousId, PaperMonitorDecisionGuard::clientOrderId($released), 'Ambiguous retry must reuse the same client_order_id.');

    // Terminal rejection/cancel gets a controlled backoff and then a new attempt id.
    $retryState = PaperMonitorDecisionGuard::applyOrder($ambiguousState, [
        'id' => 'rejected-order',
        'client_order_id' => $ambiguousId,
        'symbol' => 'AMB',
        'side' => 'sell',
        'status' => 'rejected',
    ], $now, 300);
    expectSameValue('retry_wait', PaperMonitorDecisionGuard::phase($retryState), 'Rejected close must enter retry_wait.');
    $retryEarly = PaperMonitorDecisionGuard::prepareTerminalRetryIfDue($retryState, $now->modify('+299 seconds'));
    expectSameValue($ambiguousId, PaperMonitorDecisionGuard::clientOrderId($retryEarly), 'Backoff must prevent an early new attempt id.');
    $retryReady = PaperMonitorDecisionGuard::prepareTerminalRetryIfDue($retryState, $now->modify('+301 seconds'));
    expectSameValue('pending', PaperMonitorDecisionGuard::phase($retryReady), 'Terminal retry must become pending after backoff.');
    expectTrue(PaperMonitorDecisionGuard::clientOrderId($retryReady) !== $ambiguousId, 'A terminal retry must use a new id after backoff.');
    expectTrue(strlen(PaperMonitorDecisionGuard::clientOrderId($retryReady)) <= 48, 'Retry client_order_id must fit Alpaca limit.');
    expectTrue(PaperMonitorDecisionGuard::needsPlannedOrderPersistence($retryReady, 'blocked_market_closed'), 'A new attempt must persist its own planned status once.');
    expectSameValue('pending:2', PaperMonitorDecisionGuard::alertKey($retryReady, 'pending'), 'A controlled retry must get a fresh attempt-scoped pending alert.');
    expectTrue(PaperMonitorDecisionGuard::shouldEmitAlert($retryReady, PaperMonitorDecisionGuard::alertKey($retryReady, 'pending')), 'Attempt two must not inherit attempt one delivery suppression.');

    // A partial terminal fill must reduce every retry even when the position endpoint is stale.
    $partialRetryBase = PaperMonitorDecisionGuard::ensureCloseStopEvent(openState('PRT'), closeStopDecision(), $now);
    $partialRetryBase = PaperMonitorDecisionGuard::markSubmitting($partialRetryBase, $now, 120);
    $partialRetry = PaperMonitorDecisionGuard::applyOrder($partialRetryBase, [
        'id' => 'partial-canceled-1',
        'client_order_id' => PaperMonitorDecisionGuard::clientOrderId($partialRetryBase),
        'symbol' => 'PRT',
        'side' => 'sell',
        'status' => 'canceled',
        'qty' => '150',
        'filled_qty' => '25',
        'time_in_force' => 'day',
    ], $now, 300);
    expectSameValue('retry_wait', PaperMonitorDecisionGuard::phase($partialRetry), 'A canceled partial fill must enter controlled retry.');
    expectFloat(125.0, PaperMonitorDecisionGuard::remainingExitQty($partialRetry, 150.0), 'Known fill must be deducted from a stale pre-fill position snapshot.');
    $partialRetry = PaperMonitorDecisionGuard::prepareTerminalRetryIfDue($partialRetry, $now->modify('+301 seconds'));
    expectTrue(PaperMonitorDecisionGuard::maySubmit($partialRetry, true, PaperMonitorDecisionGuard::remainingExitQty($partialRetry, 150.0)), 'Only the 125-share remainder may become retryable.');
    $partialRetry = PaperMonitorDecisionGuard::applyOrder($partialRetry, [
        'id' => 'partial-canceled-2',
        'client_order_id' => PaperMonitorDecisionGuard::clientOrderId($partialRetry),
        'symbol' => 'PRT',
        'side' => 'sell',
        'status' => 'canceled',
        'qty' => '125',
        'filled_qty' => '10',
        'time_in_force' => 'day',
    ], $now->modify('+302 seconds'), 300);
    expectFloat(115.0, PaperMonitorDecisionGuard::remainingExitQty($partialRetry, 150.0), 'Fills from separate attempts must accumulate without double counting reconciliations.');
    $samePartialRetry = PaperMonitorDecisionGuard::applyOrder($partialRetry, [
        'id' => 'partial-canceled-2',
        'client_order_id' => PaperMonitorDecisionGuard::clientOrderId($partialRetry),
        'symbol' => 'PRT',
        'side' => 'sell',
        'status' => 'canceled',
        'qty' => '125',
        'filled_qty' => '10',
        'time_in_force' => 'day',
    ], $now->modify('+303 seconds'), 300);
    expectFloat(115.0, PaperMonitorDecisionGuard::remainingExitQty($samePartialRetry, 150.0), 'Repeated order reconciliation must not count one fill twice.');
    expectTrue(!PaperMonitorDecisionGuard::maySubmit($samePartialRetry, true, 0.0), 'A zero remainder must fail closed instead of creating a sell order.');
    $staleRecoveredPartial = PaperMonitorDecisionGuard::clearRecoveredCloseStop($samePartialRetry);
    expectTrue(PaperMonitorDecisionGuard::event($staleRecoveredPartial) !== null, 'Price recovery must not forget known fills while the position snapshot still shows pre-fill quantity.');
    $reflectedRecoveredPartial = $samePartialRetry;
    $reflectedRecoveredPartial['qty'] = 115.0;
    $reflectedRecoveredPartial = PaperMonitorDecisionGuard::clearRecoveredCloseStop($reflectedRecoveredPartial);
    expectSameValue(null, PaperMonitorDecisionGuard::event($reflectedRecoveredPartial), 'A recovered stop event may clear after the position snapshot reflects every known fill.');

    $filledState = PaperMonitorDecisionGuard::applyOrder($submittingState, array_merge($acceptedOrder, ['status' => 'filled']), $now, 300);
    expectSameValue('filled', PaperMonitorDecisionGuard::phase($filledState), 'Filled close must remain guarded until position disappears.');
    expectTrue(!PaperMonitorDecisionGuard::maySubmit($filledState, true), 'Filled order plus stale position must never submit again.');

    // Alpaca's less common statuses must preserve the safe retry/guard semantics.
    $rareBase = PaperMonitorDecisionGuard::ensureCloseStopEvent(openState('RAR'), closeStopDecision(), $now);
    $rareClientId = PaperMonitorDecisionGuard::clientOrderId($rareBase);
    $rareOrder = [
        'id' => 'rare-order',
        'client_order_id' => $rareClientId,
        'symbol' => 'RAR',
        'side' => 'sell',
        'qty' => '150',
        'filled_qty' => '0',
    ];
    expectSameValue('retry_wait', PaperMonitorDecisionGuard::phase(PaperMonitorDecisionGuard::applyOrder(
        $rareBase,
        array_merge($rareOrder, ['status' => 'done_for_day', 'time_in_force' => 'day']),
        $now,
        300,
    )), 'A remaining DAY order at done_for_day must enter controlled retry.');
    expectSameValue('filled', PaperMonitorDecisionGuard::phase(PaperMonitorDecisionGuard::applyOrder(
        $rareBase,
        array_merge($rareOrder, ['status' => 'calculated', 'time_in_force' => 'day', 'filled_qty' => '150']),
        $now,
        300,
    )), 'Calculated with full filled_qty must remain filled and guarded.');
    expectSameValue('inflight', PaperMonitorDecisionGuard::phase(PaperMonitorDecisionGuard::applyOrder(
        $rareBase,
        array_merge($rareOrder, ['status' => 'calculated', 'time_in_force' => 'gtc']),
        $now,
        300,
    )), 'A remaining GTC calculated order must stay inflight, not enter retry_wait.');
    expectSameValue('inflight', PaperMonitorDecisionGuard::phase(PaperMonitorDecisionGuard::applyOrder(
        $rareBase,
        array_merge($rareOrder, ['status' => 'stopped', 'time_in_force' => 'day']),
        $now,
        300,
    )), 'Stopped must remain inflight while Alpaca can resume processing it.');
    $suspendedState = PaperMonitorDecisionGuard::applyOrder(
        $rareBase,
        array_merge($rareOrder, ['status' => 'suspended', 'time_in_force' => 'day']),
        $now,
        300,
    );
    expectSameValue('suspended', PaperMonitorDecisionGuard::phase($suspendedState), 'Suspended orders need an explicit guarded phase.');
    expectTrue(PaperMonitorDecisionGuard::shouldReconcile($suspendedState), 'Suspended orders must continue reconciliation.');
    expectSameValue('retry_wait', PaperMonitorDecisionGuard::phase(PaperMonitorDecisionGuard::applyOrder(
        $rareBase,
        array_merge($rareOrder, ['status' => 'replaced', 'time_in_force' => 'day']),
        $now,
        300,
    )), 'A replaced order without a resolvable replacement must fall back to controlled retry.');
    expectSameValue(null, PaperMonitorDecisionGuard::activeSellOrder([
        array_merge($rareOrder, ['status' => 'done_for_day', 'time_in_force' => 'day']),
    ], 'RAR'), 'A remaining DAY done_for_day order must not look active.');
    expectSameValue('rare-order', PaperMonitorDecisionGuard::activeSellOrder([
        array_merge($rareOrder, ['status' => 'calculated', 'time_in_force' => 'gtc']),
    ], 'RAR')['id'] ?? null, 'A remaining GTC calculated order must still block quantity.');

    // close_model_missing is the same guarded full-position exit path as close_stop.
    $modelDecision = closeModelDecision();
    $modelExit = PaperMonitorDecisionGuard::ensureCloseStopEvent(openState('MOD'), $modelDecision, $now);
    $modelEventId = PaperMonitorDecisionGuard::eventId($modelExit);
    $modelClientId = PaperMonitorDecisionGuard::clientOrderId($modelExit);
    expectSameValue('close_model_missing', PaperMonitorDecisionGuard::action($modelExit), 'Model-missing exits must persist their action in the shared full-exit event.');
    $modelExit = PaperMonitorDecisionGuard::markSubmitting($modelExit, $now, 120);
    $modelExit = PaperMonitorDecisionGuard::applyOrder($modelExit, [
        'id' => 'model-close-1',
        'client_order_id' => $modelClientId,
        'symbol' => 'MOD',
        'side' => 'sell',
        'status' => 'accepted',
        'qty' => '150',
    ], $now, 300);
    $modelExitAgain = PaperMonitorDecisionGuard::ensureCloseStopEvent($modelExit, $modelDecision, $now->modify('+1 minute'));
    expectSameValue($modelEventId, PaperMonitorDecisionGuard::eventId($modelExitAgain), 'Repeated model-missing polls must retain one full-exit event.');
    expectSameValue($modelClientId, PaperMonitorDecisionGuard::clientOrderId($modelExitAgain), 'Repeated model-missing polls must retain the accepted order client id.');
    expectTrue(!PaperMonitorDecisionGuard::maySubmit($modelExitAgain, true), 'An accepted model-missing exit must suppress duplicate full-qty sells.');

    // Recovery clears an unsent event; a changed stop creates a genuinely new event.
    $recovered = PaperMonitorDecisionGuard::clearRecoveredCloseStop($updatedQuote);
    expectSameValue(null, PaperMonitorDecisionGuard::event($recovered), 'Recovery must clear a pending event.');
    $changedStopState = $updatedQuote;
    $changedStopState['stop_price'] = 96.25;
    $changedStopState = PaperMonitorDecisionGuard::ensureCloseStopEvent($changedStopState, $decision, $now->modify('+2 minutes'));
    expectTrue(PaperMonitorDecisionGuard::eventId($changedStopState) !== $eventId, 'A changed stop must create a new event.');
    expectTrue(PaperMonitorDecisionGuard::clientOrderId($changedStopState) !== $clientOrderId, 'A changed stop must create a new stable attempt id.');

    // Exact USD stale-reentry regression: closed lifecycle must use the new buy metadata, never the old stop.
    $closedAt = '2026-07-14T13:32:12+00:00';
    $closedState = openState();
    $closedState['status'] = 'closed';
    $closedState['closed_at'] = $closedAt;
    $closedState['qty'] = 0.0;
    $closedState['opened_at'] = '2026-06-12T13:30:00+00:00';
    $closedState['payload']['last_review_model_missing_at'] = '2026-07-14T12:00:00+00:00';
    $closedState['payload']['paper_exit_event'] = PaperMonitorDecisionGuard::event($updatedQuote);
    $repo->savePaperPositionState($closedState);

    $oldBuy = buyOrderState('ftt_USD_older', '2026-07-14T13:00:00+00:00', [
        'stop' => 95.8878,
        'break_even_trigger' => 97.0,
        'target' => 120.0,
    ]);
    $newBuy = buyOrderState('ftt_USD_20260714_ema50', '2026-07-14T13:35:36+00:00', [
        'stop' => 80.2795,
        'break_even_trigger' => 93.4163,
        'target' => 114.1949,
    ]);
    $repo->savePaperOrderState($oldBuy);
    $repo->savePaperOrderState($newBuy);
    $entryOrder = $repo->latestSubmittedBuyOrder('USD', $closedAt);
    expectSameValue('ftt_USD_20260714_ema50', $entryOrder['client_order_id'] ?? null, 'Only a submitted buy after closed_at may seed reentry risk.');

    $signals = PaperPositionLifecycle::indexLatestSignals([
        ['date' => '2026-07-10', 'symbol' => 'USD', 'score' => 10.04, 'entry' => 95.37, 'stop' => 83.62, 'target' => 118.87, 'strategy' => 'old'],
        ['date' => '2026-07-14', 'symbol' => 'USD', 'score' => 9.44, 'entry' => 91.58, 'stop' => 80.27, 'target' => 114.19, 'strategy' => 'fresh'],
    ]);
    expectSameValue('2026-07-14', $signals['USD']['date'] ?? null, 'Freshest signal date must beat an older higher score.');

    $reentryNow = new DateTimeImmutable('2026-07-14T14:09:00+00:00');
    $newPositionState = PaperPositionLifecycle::stateFromPosition(
        ['symbol' => 'USD', 'qty' => '150', 'avg_entry_price' => '91.57', 'current_price' => '91.52'],
        $closedState,
        ['strategy' => 'stale-model', 'entry' => 99.82, 'stop' => 95.8878, 'break_even_armed' => true],
        $signals['USD'],
        $entryOrder,
        0.02,
        $reentryNow,
    );
    expectSameValue('open', $newPositionState['status'], 'Closed-to-position transition must start a new open lifecycle.');
    expectFloat(91.57, (float) $newPositionState['entry_price'], 'New entry must use actual Alpaca average.');
    expectFloat(80.2795, (float) $newPositionState['stop_price'], 'New stop must use latest submitted buy metadata.');
    expectFloat(91.57 * 1.02, (float) $newPositionState['break_even_trigger_price'], 'New BE trigger must use actual Alpaca average.');
    expectFloat(114.1949, (float) $newPositionState['target_price'], 'New target must use latest submitted buy metadata.');
    expectTrue(!(bool) $newPositionState['break_even_armed'], 'New lifecycle must reset break-even flag.');
    expectTrue(!(bool) $newPositionState['partial_done'], 'New lifecycle must reset partial flag.');
    expectTrue(!isset($newPositionState['payload']['paper_exit_event']), 'New lifecycle must discard the previous exit event.');
    expectTrue(!isset($newPositionState['payload']['last_review_model_missing_at']), 'New lifecycle must discard stale review cooldown.');
    expectSameValue(null, $newPositionState['payload']['model_position'] ?? null, 'An undated old model with a mismatched entry must be rejected for the USD reentry.');
    expectSameValue('2026-07-14', $newPositionState['payload']['signal']['date'] ?? null, 'A same-day signal whose entry matches the actual average may seed reentry risk.');
    expectSameValue('entry_order', $newPositionState['payload']['risk_source'] ?? null, 'Entry-order metadata must remain the strongest risk source.');
    expectTrue((bool) ($newPositionState['payload']['risk_source_valid'] ?? false), 'The entry-order stop must mark reentry risk as valid.');
    expectTrue(in_array('model', $newPositionState['payload']['rejected_risk_sources'] ?? [], true), 'Rejected stale model provenance must be explicit.');
    expectSameValue($reentryNow->format(DateTimeInterface::ATOM), $newPositionState['opened_at'], 'New lifecycle must get a fresh opened_at.');
    expectTrue((float) $newPositionState['market_price'] > (float) $newPositionState['stop_price'], 'The USD reentry must not trigger the stale 95.8878 stop.');

    $runnerState = openState('TRAIL');
    $runnerState['setup_key'] = 'TRAIL:setup';
    $runnerState['entry_price'] = 100.0;
    $runnerState['stop_price'] = 100.0;
    $runnerState['initial_stop_price'] = 90.0;
    $runnerState['break_even_armed'] = true;
    $runnerState['partial_done'] = true;
    $trailedRunner = PaperPositionLifecycle::stateFromPosition(
        ['symbol' => 'TRAIL', 'side' => 'long', 'qty' => '10', 'avg_entry_price' => '100', 'current_price' => '112'],
        $runnerState,
        ['key' => 'TRAIL:setup', 'entry' => 100.0, 'stop' => 106.0, 'initial_stop' => 90.0, 'took_partial' => true],
        null,
        null,
        0.02,
        $reentryNow,
    );
    expectFloat(106.0, (float) $trailedRunner['stop_price'], 'A same-lifecycle model EMA trail must ratchet the live runner stop upward.');
    $mismatchedRunner = PaperPositionLifecycle::stateFromPosition(
        ['symbol' => 'TRAIL', 'side' => 'long', 'qty' => '10', 'avg_entry_price' => '100', 'current_price' => '112'],
        $runnerState,
        ['key' => 'TRAIL:other-setup', 'entry' => 100.0, 'stop' => 108.0, 'initial_stop' => 90.0, 'took_partial' => true],
        null,
        null,
        0.02,
        $reentryNow,
    );
    expectFloat(100.0, (float) $mismatchedRunner['stop_price'], 'A different model setup must not alter the live runner stop.');

    $repo->savePaperPositionState($newPositionState);
    $reloadedNewPosition = $repo->loadPaperPositionStates()['USD'] ?? [];
    expectSameValue($reentryNow->format(DateTimeInterface::ATOM), $reloadedNewPosition['opened_at'] ?? null, 'SQLite upsert must replace opened_at on closed-to-open lifecycle.');
    expectFloat(80.2795, (float) ($reloadedNewPosition['stop_price'] ?? 0.0), 'SQLite must persist the new lifecycle stop.');

    // A model can seed a closed-to-open lifecycle only when its entry provenance proves it is current.
    $freshModelClosed = openState('NEW');
    $freshModelClosed['status'] = 'closed';
    $freshModelClosed['qty'] = 0.0;
    $freshModelClosed['closed_at'] = '2026-07-14T13:32:12+00:00';
    $freshModel = [
        'symbol' => 'NEW',
        'entry_date' => '2026-07-15',
        'entry' => 50.75,
        'initial_stop' => 44.5,
        'stop' => 48.0,
        'target' => 62.0,
        'strategy' => 'fresh-model',
        'key' => 'NEW:fresh-model',
    ];
    $freshModelState = PaperPositionLifecycle::stateFromPosition(
        ['symbol' => 'NEW', 'qty' => '75', 'avg_entry_price' => '50.00', 'current_price' => '51.00'],
        $freshModelClosed,
        $freshModel,
        null,
        null,
        0.02,
        new DateTimeImmutable('2026-07-15T14:00:00+00:00'),
    );
    expectFloat(44.5, (float) $freshModelState['stop_price'], 'A model entry day after the prior close may supply the new initial stop.');
    expectFloat(62.0, (float) $freshModelState['target_price'], 'A proven-current model may supply the new target.');
    expectSameValue($freshModel, $freshModelState['payload']['model_position'] ?? null, 'A proven-current model must remain in lifecycle payload.');
    expectSameValue('model', $freshModelState['payload']['risk_source'] ?? null, 'Fresh model provenance must be recorded.');
    expectTrue((bool) ($freshModelState['payload']['risk_source_valid'] ?? false), 'A fresh model stop must mark risk as valid.');
    expectTrue(!PaperPositionLifecycle::requiresRiskSourceReview($freshModelState, true), 'A managed lifecycle with proven-current model risk must not raise a review alert.');

    $sameDayMatchingModel = [
        'symbol' => 'USD',
        'entry_date' => '2026-07-14',
        'entry' => 91.60,
        'initial_stop' => 80.5,
        'target' => 114.0,
        'strategy' => 'same-day-current',
    ];
    $sameDayModelState = PaperPositionLifecycle::stateFromPosition(
        ['symbol' => 'USD', 'qty' => '150', 'avg_entry_price' => '91.57', 'current_price' => '91.52'],
        $closedState,
        $sameDayMatchingModel,
        null,
        null,
        0.02,
        $reentryNow,
    );
    expectFloat(80.5, (float) $sameDayModelState['stop_price'], 'A same-day model may seed risk when its entry conservatively matches the Alpaca average.');
    $sameDayMismatchedModel = $sameDayMatchingModel;
    $sameDayMismatchedModel['entry'] = 99.82;
    $sameDayMismatchedModel['initial_stop'] = 95.8878;
    $mismatchedModelState = PaperPositionLifecycle::stateFromPosition(
        ['symbol' => 'USD', 'qty' => '150', 'avg_entry_price' => '91.57', 'current_price' => '91.52'],
        $closedState,
        $sameDayMismatchedModel,
        null,
        null,
        0.02,
        $reentryNow,
    );
    expectFloat(0.0, (float) $mismatchedModelState['stop_price'], 'A same-day model with a mismatched entry must remain rejected as stale.');
    expectSameValue(null, $mismatchedModelState['payload']['model_position'] ?? null, 'A rejected same-day model must not remain as lifecycle provenance.');

    $staleRiskPosition = ['symbol' => 'USD', 'qty' => '150', 'avg_entry_price' => '91.57', 'current_price' => '91.52'];
    $staleRiskSignal = ['date' => '2026-07-10', 'symbol' => 'USD', 'entry' => 99.82, 'stop' => 95.8878, 'target' => 120.0];
    $staleSignalState = PaperPositionLifecycle::stateFromPosition(
        $staleRiskPosition,
        $closedState,
        null,
        $staleRiskSignal,
        null,
        0.02,
        $reentryNow,
    );
    expectFloat(0.0, (float) $staleSignalState['stop_price'], 'An older signal must not resurrect stale risk on a new lifecycle.');
    expectSameValue(null, $staleSignalState['payload']['signal'] ?? null, 'Rejected stale signal data must not be presented as lifecycle provenance.');
    expectTrue(!(bool) ($staleSignalState['payload']['risk_source_valid'] ?? true), 'Missing valid entry/model/signal risk must be explicit for the managed guard.');
    expectTrue(in_array('signal', $staleSignalState['payload']['rejected_risk_sources'] ?? [], true), 'Rejected stale signal provenance must be explicit.');
    expectTrue(PaperPositionLifecycle::requiresRiskSourceReview($staleSignalState, true), 'A raw managed position with rejected risk sources must raise a review alert.');
    expectTrue(!PaperPositionLifecycle::requiresRiskSourceReview($staleSignalState, false), 'An unmanaged position must retain the separate model-missing review path.');
    $staleSignalSecondPoll = PaperPositionLifecycle::stateFromPosition(
        $staleRiskPosition,
        $staleSignalState,
        null,
        $staleRiskSignal,
        null,
        0.02,
        $reentryNow->modify('+1 minute'),
    );
    expectFloat(0.0, (float) $staleSignalSecondPoll['stop_price'], 'A rejected stale signal must remain rejected on later polls of the same lifecycle.');
    expectTrue(PaperPositionLifecycle::requiresRiskSourceReview($staleSignalSecondPoll, true), 'The invalid-risk review guard must persist until a current source arrives.');
    $riskRecoveredState = PaperPositionLifecycle::stateFromPosition(
        $staleRiskPosition,
        $staleSignalSecondPoll,
        null,
        $signals['USD'],
        null,
        0.02,
        $reentryNow->modify('+2 minutes'),
    );
    expectFloat(80.27, (float) $riskRecoveredState['stop_price'], 'A later proven-current signal must recover an invalid-risk lifecycle safely.');
    expectTrue(!PaperPositionLifecycle::requiresRiskSourceReview($riskRecoveredState, true), 'The review guard must clear after a valid stop source arrives.');

    // Fast close-to-reentry: a newer buy must reset even if no closed position snapshot was observed.
    $closingState = PaperMonitorDecisionGuard::ensureCloseStopEvent(openState(), $decision, new DateTimeImmutable('2026-07-14T13:30:00+00:00'));
    $closingState = PaperMonitorDecisionGuard::markSubmitting($closingState, new DateTimeImmutable('2026-07-14T13:30:02+00:00'), 120);
    $closingState = PaperMonitorDecisionGuard::applyOrder($closingState, [
        'id' => 'old-close-filled',
        'client_order_id' => PaperMonitorDecisionGuard::clientOrderId($closingState),
        'symbol' => 'USD',
        'side' => 'sell',
        'status' => 'filled',
        'qty' => '150',
        'filled_qty' => '150',
        'filled_at' => '2026-07-14T13:30:06+00:00',
    ], new DateTimeImmutable('2026-07-14T13:30:06+00:00'), 300);
    $reentryBoundary = PaperPositionLifecycle::reentrySearchAfter($closingState);
    expectSameValue('2026-07-14T13:30:06+00:00', $reentryBoundary, 'A closing lifecycle must search for buys after its latest exit evidence.');
    $fastEntryOrder = $repo->latestSubmittedBuyOrder('USD', $reentryBoundary);
    expectSameValue('ftt_USD_20260714_ema50', $fastEntryOrder['client_order_id'] ?? null, 'The buy after a filled exit must be detected without an intermediate closed snapshot.');
    $fastPosition = ['symbol' => 'USD', 'qty' => '150', 'avg_entry_price' => '91.57', 'current_price' => '91.52'];
    $staleUnchangedPosition = ['symbol' => 'USD', 'qty' => '150', 'avg_entry_price' => '99.82', 'current_price' => '95.00'];
    expectTrue(
        !PaperPositionLifecycle::shouldResetForReentry($closingState, $staleUnchangedPosition, $fastEntryOrder),
        'A pending unfilled buy plus an unchanged stale position snapshot must retain the filled exit guard.',
    );
    $stillFilledGuarded = PaperPositionLifecycle::stateFromPosition(
        $staleUnchangedPosition,
        $closingState,
        null,
        null,
        $fastEntryOrder,
        0.02,
        $reentryNow,
    );
    expectSameValue('closing', $stillFilledGuarded['status'], 'Without reentry evidence, lifecycle state must remain closing.');
    expectSameValue('filled', PaperMonitorDecisionGuard::phase($stillFilledGuarded), 'The old filled exit event must survive an unchanged stale snapshot.');

    $filledEntryEvidence = $fastEntryOrder;
    $filledEntryEvidence['status'] = 'filled';
    expectTrue(
        PaperPositionLifecycle::shouldResetForReentry($closingState, $staleUnchangedPosition, $filledEntryEvidence),
        'A filled entry order is sufficient reentry evidence even before the position snapshot changes.',
    );

    $acceptedExitState = PaperMonitorDecisionGuard::ensureCloseStopEvent(openState(), $decision, new DateTimeImmutable('2026-07-14T13:30:00+00:00'));
    $acceptedExitState = PaperMonitorDecisionGuard::markSubmitting($acceptedExitState, new DateTimeImmutable('2026-07-14T13:30:02+00:00'), 120);
    $acceptedExitState = PaperMonitorDecisionGuard::applyOrder($acceptedExitState, [
        'id' => 'old-close-accepted',
        'client_order_id' => PaperMonitorDecisionGuard::clientOrderId($acceptedExitState),
        'symbol' => 'USD',
        'side' => 'sell',
        'status' => 'accepted',
        'qty' => '150',
        'filled_qty' => '0',
    ], new DateTimeImmutable('2026-07-14T13:30:06+00:00'), 300);
    expectTrue(
        !PaperPositionLifecycle::shouldResetForReentry($acceptedExitState, $fastPosition, $filledEntryEvidence),
        'An accepted/inflight exit must never be cleared as reentry while it can still sell the new shares.',
    );

    expectTrue(PaperPositionLifecycle::shouldResetForReentry($closingState, $fastPosition, $fastEntryOrder), 'A newer buy after filled close must force a fresh lifecycle.');
    $fastReentryState = PaperPositionLifecycle::stateFromPosition(
        $fastPosition,
        $closingState,
        ['strategy' => 'stale-model', 'entry' => 99.82, 'stop' => 95.8878, 'break_even_armed' => true],
        $signals['USD'],
        $fastEntryOrder,
        0.02,
        $reentryNow,
        true,
    );
    expectSameValue('open', $fastReentryState['status'], 'Forced fast reentry must reopen lifecycle state.');
    expectFloat(80.2795, (float) $fastReentryState['stop_price'], 'Fast reentry must use new buy metadata, never the filled lifecycle stop.');
    expectTrue(PaperMonitorDecisionGuard::event($fastReentryState) === null, 'Fast reentry must discard the filled exit event.');
    expectTrue(($fastReentryState['payload']['position_lifecycle_id'] ?? '') !== ($closingState['payload']['position_lifecycle_id'] ?? ''), 'Fast reentry must get the newer buy lifecycle id.');

    $rejectedBuy = buyOrderState('ftt_USD_rejected_newer', '2026-07-14T13:36:00+00:00', ['stop' => 70.0, 'target' => 130.0]);
    $rejectedBuy['status'] = 'rejected';
    $repo->savePaperOrderState($rejectedBuy);
    expectSameValue('ftt_USD_20260714_ema50', $repo->latestSubmittedBuyOrder('USD', $closedAt)['client_order_id'] ?? null, 'Rejected newer buys must never seed a lifecycle.');

    $filledAfterBoundary = buyOrderState('ftt_USD_filled_after_boundary', '2026-07-14T13:29:00+00:00', ['stop' => 79.5, 'target' => 115.0]);
    $filledAfterBoundary['status'] = 'filled';
    $filledAfterBoundary['payload']['alpaca_order']['filled_at'] = '2026-07-14T13:37:00+00:00';
    $repo->savePaperOrderState($filledAfterBoundary);
    expectSameValue(
        'ftt_USD_filled_after_boundary',
        $repo->latestSubmittedBuyOrder('USD', $closedAt)['client_order_id'] ?? null,
        'A buy submitted before the boundary but filled after it must be eligible and ordered by filled_at.',
    );

    // One lock path must exclude both daemon and standalone invocations without waiting.
    $lockPath = $databasePath . '.lock';
    $firstLock = ProcessLock::tryAcquire($lockPath);
    expectTrue($firstLock !== null, 'The first monitor process must acquire the lock.');
    expectSameValue(null, ProcessLock::tryAcquire($lockPath), 'A concurrent monitor invocation must exit instead of overlapping.');
    $duplicateProcess = proc_open(
        [PHP_BINARY, __DIR__ . '/../tools/paper_position_monitor.php', '--lock=' . $lockPath],
        [1 => ['pipe', 'w'], 2 => ['pipe', 'w']],
        $duplicatePipes,
        dirname(__DIR__),
    );
    expectTrue(is_resource($duplicateProcess), 'The duplicate monitor regression process must start.');
    $duplicateStdout = stream_get_contents($duplicatePipes[1]);
    $duplicateStderr = stream_get_contents($duplicatePipes[2]);
    fclose($duplicatePipes[1]);
    fclose($duplicatePipes[2]);
    $duplicateExit = proc_close($duplicateProcess);
    expectSameValue(75, $duplicateExit, 'A skipped monitor pass must return EX_TEMPFAIL so daemon/install cannot report it as healthy.');
    expectTrue(
        str_contains((string) $duplicateStderr . (string) $duplicateStdout, 'already running'),
        'Lock contention must remain explicit to a manual caller.',
    );
    $firstLock->release();
    $nextLock = ProcessLock::tryAcquire($lockPath);
    expectTrue($nextLock !== null, 'The lock must be reusable after the first process exits.');
    $nextLock->release();
    @unlink($lockPath);
} finally {
    unset($repo);
    @unlink($databasePath);
}

echo "Paper monitor close-stop safety OK\n";
