<?php

declare(strict_types=1);

return [
    'database_path' => __DIR__ . '/../var/db/trading.sqlite',
    'cache_path' => __DIR__ . '/../var/cache',
    'data' => [
        'alpaca' => [
            'base_url' => 'https://data.alpaca.markets',
            'feed' => 'iex',
            'adjustment' => 'split',
            'limit' => 10000,
        ],
        'stooq' => [
            'base_url' => 'https://stooq.com/q/d/l/',
        ],
        'yahoo' => [
            'base_url' => 'https://query1.finance.yahoo.com',
        ],
    ],
    'trading' => [
        'alpaca' => [
            'paper_base_url' => 'https://paper-api.alpaca.markets/v2',
            'live_base_url' => 'https://api.alpaca.markets/v2',
            'paper_only' => true,
            'orders_enabled' => true,
        ],
    ],
    'strategy' => [
        'ema_periods' => [10, 20, 21, 50, 100, 200],
        'atr_period' => 14,
        'volume_avg_period' => 50,
        'rocket_lookback' => 63,
        'rocket_min_gain_pct' => 0.60,
        'volume_spike_multiple' => 1.8,
        'first_pullback_lookback' => 20,
        'ema_touch_tolerance_pct' => 0.01,
        'max_distance_to_ema_pct' => 0.18,
        'order_valid_bars' => 10,
        'target_r_multiple' => 1.5,
        'partial_take_profit_pct' => 0.25,
        'support_regularity' => [
            'enabled' => true,
            'weekly_enabled' => true,
            'periods' => [10, 20, 30, 50, 100, 150, 200],
            'weekly_periods' => [10, 20, 50, 100, 200],
            'types' => ['ema', 'sma'],
            'lookback_bars' => 504,
            'weekly_lookback_bars' => 156,
            'forward_bars' => 20,
            'weekly_forward_bars' => 8,
            'min_touches' => 3,
            'min_success_rate' => 0.60,
            'success_min_return_pct' => 0.03,
            'touch_tolerance_pct' => 0.015,
            'violation_tolerance_pct' => 0.03,
            'near_pct' => 0.025,
            'near_atr_multiple' => 0.60,
            'stop_atr_multiple' => 1.5,
            'target_atr_multiple' => 3.0,
            'cooldown_bars' => 10,
            'require_close_above_support' => false,
        ],
        'short_resistance' => [
            'enabled' => false,
            'periods' => [10, 20, 30, 50, 100, 150, 200],
            'types' => ['ema', 'sma'],
            'lookback_bars' => 504,
            'forward_bars' => 20,
            'min_touches' => 3,
            'min_success_rate' => 0.60,
            'success_min_return_pct' => 0.03,
            'touch_tolerance_pct' => 0.015,
            'violation_tolerance_pct' => 0.03,
            'near_pct' => 0.025,
            'near_atr_multiple' => 0.60,
            'stop_atr_multiple' => 1.5,
            'target_atr_multiple' => 3.0,
            'cooldown_bars' => 10,
            'require_close_below_resistance' => false,
            'max_market_score' => 2.0,
        ],
        'short_symbols' => [],
        'inverse_long_symbols' => [],
        'inverse_long' => [
            'max_market_score' => 2.0,
        ],
        'market_dip_entry' => [
            'enabled' => false,
            'only' => false,
            'min_spy_drawdown_pct' => 0.08,
            'max_spy_drawdown_pct' => 0.30,
            'max_market_score' => 2.5,
            'max_spy_rsi14' => 45.0,
        ],
        'order_fill_mode' => 'same_day_touch',
        'layered_positions' => [
            'enabled' => true,
            'require_green_garden' => true,
            'same_symbol_max_layers' => 3,
            'green_garden_profit_pct' => 0.01,
            'break_even_add_on' => [
                'enabled' => false,
                'position_fraction' => 1.0,
            ],
            'support_hierarchy_sizing' => [
                'enabled' => true,
                'max_position_pct' => 1.50,
                'multipliers' => [
                    'D' => [
                        10 => 0.75,
                        20 => 1.00,
                        30 => 1.00,
                        50 => 1.15,
                        100 => 1.25,
                        150 => 1.30,
                        200 => 1.35,
                    ],
                    'W' => [
                        10 => 1.25,
                        20 => 1.40,
                        50 => 1.50,
                        100 => 1.50,
                        200 => 1.50,
                    ],
                ],
            ],
        ],
        'family_exposure_caps' => [
            'enabled' => true,
            'default_max_gross_exposure_pct' => 1.00,
            'caps' => [
                'SP500' => 1.00,
                'NASDAQ_100' => 1.00,
                'SEMICONDUCTORS' => 1.00,
                'TECH' => 1.00,
                'MEGA_GROWTH' => 1.00,
            ],
        ],
        'reentry_after_stop' => [
            'enabled' => true,
            'cooldown_days' => 3,
            'require_stronger_support' => true,
            'allow_same_strength_after_days' => 30,
        ],
        'external_filters' => [
            'enabled' => true,
            'require_history' => false,
            'required_indicators' => ['fbma', 'fbma20'],
            'timeframes' => ['1D', 'D', '1W', 'W'],
            'bullish_signals' => ['buy', 'long', 'bull', 'bullish', 'green', 'ok', 'support', 'подтверждено', 'покупка', 'лонг'],
        ],
        'club_rules' => [
            'enabled' => true,
            'break_even_profit_pct' => 0.02,
            'break_even_trigger_mode' => 'high',
            'break_even_stop_mode' => 'hard',
            'break_even_stop_offset_pct' => 0.0,
            'default_swing_stop_mode' => 'mental',
            'hard_stop_fill_mode' => 'gap_open',
            'hybrid_hard_stop_symbols' => ['UPRO', 'SPXL', 'SPUU', 'SSO', 'TQQQ', 'QLD', 'SOXL', 'USD', 'TECL', 'ROM', 'UDOW', 'TNA', 'FAS', 'FNGU', 'BULZ', 'MSFU', 'MSFX'],
            'hard_stop_label_required' => true,
            'mental_stop_exit_on_close' => true,
            'max_gross_exposure_pct' => 2.0,
            'unstable_market_position_pct' => 0.05,
            'stable_market_position_pct' => 1.0,
            'stable_market_score_threshold' => 2.5,
            'unstable_warning_count' => 3,
            'strategy_violation_question' => 'strategy_on_chart_broken',
        ],
        'market' => [
            'symbols' => [
                'SPY', 'QQQ', 'SMH', 'RSP', 'IWM', 'DIA',
                'XLK', 'XLY', 'XLC', 'XLF', 'XLI', 'XLV', 'XLE', 'XLP', 'XLU', 'XLRE', 'XLB',
                'AAPL', 'MSFT', 'NVDA', 'AMZN', 'META', 'GOOGL', 'AVGO', 'TSLA',
            ],
            'require_spy_above_ema20' => true,
            'require_qqq_above_ema20' => false,
            'atr_break_buffer' => 0.20,
            'symbol_weights' => [
                'SPY' => 2.0,
                'QQQ' => 1.0,
                'SMH' => 0.8,
                'RSP' => 0.8,
                'IWM' => 0.5,
                'DIA' => 0.4,
                'XLK' => 0.5,
                'XLY' => 0.35,
                'XLC' => 0.35,
                'XLF' => 0.35,
                'XLI' => 0.35,
                'XLV' => 0.35,
                'XLE' => 0.25,
                'XLP' => 0.25,
                'XLU' => 0.25,
                'XLRE' => 0.25,
                'XLB' => 0.25,
                'AAPL' => 0.25,
                'MSFT' => 0.25,
                'NVDA' => 0.25,
                'AMZN' => 0.20,
                'META' => 0.20,
                'GOOGL' => 0.20,
                'AVGO' => 0.15,
                'TSLA' => 0.15,
            ],
            'warning_ema20_symbols' => ['RSP', 'IWM', 'XLK', 'XLY', 'XLF', 'XLI', 'XLV', 'AAPL', 'MSFT', 'NVDA'],
        ],
        'dashboard' => [
            'codes' => [
                'S5FD', 'S5TW', 'S5FI', 'S5OH', 'S5TH',
                'NDFD', 'NDTW', 'NDFI', 'NDOH', 'NDTH',
                'DIFD', 'DITW', 'DIFI', 'DIOH', 'DITH',
            ],
        ],
        'external_indicators' => [
            'tradingview_layouts' => [
                'daily_1' => 'https://ru.tradingview.com/chart/4ojdXa4Z/',
                'daily_2' => 'https://ru.tradingview.com/chart/x5Hg6Nje/',
                'daily_3' => 'https://ru.tradingview.com/chart/l3IB8uPe/',
                'daily_4' => 'https://ru.tradingview.com/chart/6zrDPYR1/',
                'daily_5' => 'https://ru.tradingview.com/chart/pO78XXBP/',
                'daily_6' => 'https://ru.tradingview.com/chart/WqMWT2GG/',
                'daily_7' => 'https://ru.tradingview.com/chart/F9OnQyPg/',
                'four_hour' => 'https://ru.tradingview.com/chart/hsh1A5ke/',
                'fifteen_minute' => 'https://ru.tradingview.com/chart/R2wTgb1r/',
                'weekly' => 'https://ru.tradingview.com/chart/0vXdT7XU/',
            ],
            'scripts' => [
                'seasonality_presidential_cycle' => 'https://ru.tradingview.com/script/psG4Vj0S-seasonality-and-presidential-cycle/',
                'fbma' => 'https://ru.tradingview.com/script/2lwYNmF2-fbma/',
                'fbma20' => 'https://ru.tradingview.com/script/cVfxQDkQ-fbma-20/',
            ],
            'required_for_live' => ['fbma', 'fbma20', 'seasonality_presidential_cycle'],
            'market_context' => [
                'VIX', 'VVIX', 'SVXY', 'SVIX', 'DXY', 'US20Y', 'PCC', 'PCSP', 'M2SL',
                'SPY', 'QQQ', 'SMH', 'RSP', 'DIA', 'IWM', 'XLK', 'XLF', 'XLI', 'XLV', 'XLY', 'XLC',
                'MAGS', 'AAPL', 'MSFT', 'NVDA', 'AMZN', 'META', 'GOOGL', 'AVGO', 'TSLA',
            ],
        ],
    ],
    'watchlists' => [
        'us_stocks' => [
            'AAPL', 'MSFT', 'NVDA', 'AMZN', 'META', 'GOOGL', 'AVGO', 'TSLA',
            'AMD', 'NFLX', 'CRM', 'ADBE', 'COST', 'ORCL', 'NOW', 'PLTR',
            'LLY', 'UNH', 'JPM', 'V', 'MA', 'XOM', 'CAT', 'GE', 'UBER',
            'PANW', 'CRWD', 'SHOP', 'MELI', 'SMCI', 'MU', 'COIN',
        ],
    ],
    'risk' => [
        'initial_cash' => 30000.0,
        'position_sizing_mode' => 'capital_pct',
        'fixed_position_usd' => 0.0,
        'risk_per_trade_pct' => 0.005,
        'max_position_pct' => 1.0,
        'max_open_positions' => 4,
        'allow_fractional_shares' => true,
        'paper_only' => true,
    ],
];
